# Generated by Django 6.0.5 on 2026-07-29 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RolPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('puede_gestionar_productos', models.BooleanField(default=True)),
                ('puede_gestionar_pedidos', models.BooleanField(default=True)),
                ('puede_gestionar_clientes', models.BooleanField(default=True)),
                ('puede_gestionar_proveedores', models.BooleanField(default=True)),
                ('puede_gestionar_compras', models.BooleanField(default=True)),
                ('puede_gestionar_pagos', models.BooleanField(default=True)),
                ('puede_gestionar_envios', models.BooleanField(default=True)),
                ('puede_gestionar_inventario', models.BooleanField(default=True)),
                ('puede_ver_reportes', models.BooleanField(default=True)),
                ('puede_ver_dashboard', models.BooleanField(default=True)),
                ('puede_gestionar_configuracion', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Rol de Panel',
                'verbose_name_plural': 'Roles de Panel',
                'db_table': 'admin_panel_rol',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='admin_panel.rolpanel')),
                ('usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='rol_panel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario de Panel',
                'verbose_name_plural': 'Usuarios de Panel',
                'db_table': 'admin_panel_usuario',
                'ordering': ['-fecha_asignacion'],
            },
        ),
    ]
