# Generated by Django 5.2.14 on 2026-08-10 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('es_producto_propio', models.BooleanField(default=False)),
                ('fecha_compra', models.DateField()),
                ('numero_factura', models.CharField(blank=True, max_length=50)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('recibida', 'Recibida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'admin_panel_compra',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Item de Compra',
                'verbose_name_plural': 'Items de Compra',
                'db_table': 'admin_panel_item_compra',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('entrada_compra', 'Entrada por Compra'), ('entrada_devolucion', 'Entrada por Devolución'), ('salida_venta', 'Salida por Venta'), ('salida_merma', 'Salida por Merma/Pérdida'), ('salida_ajuste', 'Salida por Ajuste de Inventario'), ('entrada_ajuste', 'Entrada por Ajuste de Inventario')], max_length=30)),
                ('cantidad', models.IntegerField()),
                ('stock_anterior', models.IntegerField()),
                ('stock_posterior', models.IntegerField()),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'admin_panel_movimiento_inventario',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=200, verbose_name='Empresa')),
                ('rfc', models.CharField(max_length=13, verbose_name='RFC')),
                ('contacto', models.CharField(max_length=150, verbose_name='Persona de contacto')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('whatsapp', models.CharField(blank=True, max_length=15)),
                ('calle', models.CharField(blank=True, max_length=200)),
                ('numero_exterior', models.CharField(blank=True, max_length=10)),
                ('colonia', models.CharField(blank=True, max_length=100)),
                ('municipio', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('pagina_web', models.URLField(blank=True)),
                ('tiempo_entrega', models.PositiveIntegerField(default=7, verbose_name='Tiempo de entrega (días)')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('condiciones_pago', models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito'), ('mixto', 'Mixto')], default='contado', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'admin_panel_proveedor',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RolPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('puede_gestionar_productos', models.BooleanField(default=True)),
                ('puede_gestionar_pedidos', models.BooleanField(default=True)),
                ('puede_gestionar_clientes', models.BooleanField(default=True)),
                ('puede_gestionar_proveedores', models.BooleanField(default=True)),
                ('puede_gestionar_compras', models.BooleanField(default=True)),
                ('puede_gestionar_pagos', models.BooleanField(default=True)),
                ('puede_gestionar_envios', models.BooleanField(default=True)),
                ('puede_gestionar_inventario', models.BooleanField(default=True)),
                ('puede_gestionar_direcciones_envio', models.BooleanField(default=False)),
                ('puede_ver_reportes', models.BooleanField(default=True)),
                ('puede_ver_dashboard', models.BooleanField(default=True)),
                ('puede_gestionar_configuracion', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Rol de Panel',
                'verbose_name_plural': 'Roles de Panel',
                'db_table': 'admin_panel_rol',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuario de Panel',
                'verbose_name_plural': 'Usuarios de Panel',
                'db_table': 'admin_panel_usuario',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialProducto',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_cambio', models.CharField(choices=[('creacion', 'Creación de Producto'), ('actualizacion', 'Actualización de Datos'), ('cambio_precio', 'Cambio de Precio'), ('cambio_stock', 'Cambio de Stock'), ('cambio_estado', 'Cambio de Estado (Activo/Inactivo)'), ('cambio_costo', 'Cambio de Costo Promedio'), ('actualizacion_imagen', 'Actualización de Imagen')], max_length=30)),
                ('campos_cambiados', models.JSONField(blank=True, default=dict)),
                ('precio_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(blank=True, db_column='id_compra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales', to='admin_panel.compra')),
            ],
            options={
                'verbose_name': 'Historial de Producto',
                'verbose_name_plural': 'Historiales de Productos',
                'db_table': 'admin_panel_historial_producto',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
