# Generated by Django 6.0.5 on 2026-07-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=200, verbose_name='Empresa')),
                ('rfc', models.CharField(max_length=13, verbose_name='RFC')),
                ('contacto', models.CharField(max_length=150, verbose_name='Persona de contacto')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('whatsapp', models.CharField(blank=True, max_length=15)),
                ('calle', models.CharField(blank=True, max_length=200)),
                ('numero_exterior', models.CharField(blank=True, max_length=10)),
                ('colonia', models.CharField(blank=True, max_length=100)),
                ('municipio', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('pagina_web', models.URLField(blank=True)),
                ('tiempo_entrega', models.PositiveIntegerField(default=7, verbose_name='Tiempo de entrega (días)')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('condiciones_pago', models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito'), ('mixto', 'Mixto')], default='contado', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'admin_panel_proveedor',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
