# Generated by Django 5.2.14 on 2026-08-10 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('pedidos', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialproducto',
            name='pedido',
            field=models.ForeignKey(blank=True, db_column='id_pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales', to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='historialproducto',
            name='producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='historialproducto',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_productos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemcompra',
            name='compra',
            field=models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='admin_panel.compra'),
        ),
        migrations.AddField(
            model_name='itemcompra',
            name='producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='items_compra', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='compra',
            field=models.ForeignKey(blank=True, db_column='id_compra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='admin_panel.compra'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='pedido',
            field=models.ForeignKey(blank=True, db_column='id_pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inventario', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialproducto',
            name='movimiento_inventario',
            field=models.ForeignKey(blank=True, db_column='id_movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales', to='admin_panel.movimientoinventario'),
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(blank=True, db_column='id_proveedor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='admin_panel.proveedor'),
        ),
        migrations.AddField(
            model_name='usuariopanel',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='admin_panel.rolpanel'),
        ),
        migrations.AddField(
            model_name='usuariopanel',
            name='usuario',
            field=models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='rol_panel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='historialproducto',
            index=models.Index(fields=['producto', '-fecha_cambio'], name='admin_panel_id_prod_cb0bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='historialproducto',
            index=models.Index(fields=['tipo_cambio', '-fecha_cambio'], name='admin_panel_tipo_ca_bb333b_idx'),
        ),
    ]
