# Generated by Django 6.0.5 on 2026-07-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_crear_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolpanel',
            name='puede_gestionar_direcciones_envio',
            field=models.BooleanField(default=False),
        ),
    ]
