# Generated by Django 6.0.5 on 2026-07-30 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_rolpanel_puede_gestionar_direcciones_envio'),
        ('productos', '0005_producto_id_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('es_producto_propio', models.BooleanField(default=False)),
                ('fecha_compra', models.DateField()),
                ('numero_factura', models.CharField(blank=True, max_length=50)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('recibida', 'Recibida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(blank=True, db_column='id_proveedor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='admin_panel.proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'admin_panel_compra',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='admin_panel.compra')),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='items_compra', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Item de Compra',
                'verbose_name_plural': 'Items de Compra',
                'db_table': 'admin_panel_item_compra',
            },
        ),
    ]
