# Generated by Django 6.0.5 on 2026-07-30 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_compra_itemcompra'),
        ('pedidos', '0008_pago_metodo_mercadopago'),
        ('productos', '0005_producto_id_proveedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('entrada_compra', 'Entrada por Compra'), ('entrada_devolucion', 'Entrada por Devolución'), ('salida_venta', 'Salida por Venta'), ('salida_merma', 'Salida por Merma/Pérdida'), ('salida_ajuste', 'Salida por Ajuste de Inventario'), ('entrada_ajuste', 'Entrada por Ajuste de Inventario')], max_length=30)),
                ('cantidad', models.IntegerField()),
                ('stock_anterior', models.IntegerField()),
                ('stock_posterior', models.IntegerField()),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(blank=True, db_column='id_compra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='admin_panel.compra')),
                ('pedido', models.ForeignKey(blank=True, db_column='id_pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='pedidos.pedido')),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inventario', to='productos.producto')),
                ('usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'admin_panel_movimiento_inventario',
                'ordering': ['-fecha_movimiento'],
            },
        ),
    ]
