# Generated by Django 5.2.14 on 2026-08-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id_carrito_item', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ítem de carrito',
                'verbose_name_plural': 'Ítems de carrito',
                'db_table': 'pedidos_carrito_item',
            },
        ),
        migrations.CreateModel(
            name='ComentarioProducto',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField(choices=[(1, '1 estrella – Muy malo'), (2, '2 estrellas – Malo'), (3, '3 estrellas – Regular'), (4, '4 estrellas – Bueno'), (5, '5 estrellas – Excelente')])),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('comentario', models.TextField()),
                ('imagen_1', models.ImageField(blank=True, null=True, upload_to='comentarios/')),
                ('imagen_2', models.ImageField(blank=True, null=True, upload_to='comentarios/')),
                ('imagen_3', models.ImageField(blank=True, null=True, upload_to='comentarios/')),
                ('compra_verificada', models.BooleanField(default=False)),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('respuesta_vendedor', models.TextField(blank=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'pedidos_comentario_producto',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('paqueteria', models.CharField(db_column='paqueteria', default='', max_length=50)),
                ('transportista', models.CharField(blank=True, max_length=100)),
                ('servicio', models.CharField(blank=True, max_length=100)),
                ('numero_guia', models.CharField(blank=True, db_column='numero_guia', help_text='Número de rastreo proporcionado por la paquetería externa', max_length=100, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('respuesta_json', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de asignación'), ('en_ruta', 'En camino'), ('en_transito', 'En tránsito'), ('entregado', 'Entregado'), ('incidente', 'Incidente reportado')], default='pendiente', max_length=20)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('ubicacion_actual', models.CharField(blank=True, max_length=255)),
                ('notas_entrega', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'db_table': 'pedidos_entrega',
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id_item_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Ítem de pedido',
                'verbose_name_plural': 'Ítems de pedido',
                'db_table': 'pedidos_item_pedido',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'pedidos_notificacion',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('proveedor_pago', models.CharField(default='manual', max_length=50)),
                ('metodo', models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('oxxo', 'Pago en OXXO'), ('tarjeta', 'Stripe'), ('mercadopago', 'Mercado Pago')], default='transferencia', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('pagado', 'Pagado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/')),
                ('ultimos_digitos', models.CharField(blank=True, max_length=4)),
                ('nombre_titular', models.CharField(blank=True, max_length=200)),
                ('fecha_expiracion', models.CharField(blank=True, max_length=7)),
                ('referencia_oxxo', models.CharField(blank=True, max_length=18, null=True)),
                ('fecha_vencimiento_oxxo', models.DateTimeField(blank=True, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('referencia_pago', models.CharField(blank=True, max_length=100)),
                ('mercadopago_payment_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pedidos_pago',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('preparando', 'En preparación'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('pagado', 'Pagado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('nombre_receptor', models.CharField(blank=True, max_length=200)),
                ('telefono_contacto', models.CharField(blank=True, max_length=15)),
                ('direccion_entrega', models.TextField(blank=True)),
                ('numero_rastreo', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('mensaje_estado', models.TextField(blank=True, help_text='Mensaje adicional para el cliente sobre su pedido')),
                ('estado_cancelacion', models.CharField(choices=[('sin_solicitud', 'Sin solicitud'), ('solicitado', 'Cancelación solicitada'), ('aprobado', 'Cancelación aprobada'), ('rechazado', 'Cancelación rechazada')], default='sin_solicitud', max_length=20)),
                ('motivo_cancelacion', models.TextField(blank=True)),
                ('razon_rechazo', models.TextField(blank=True)),
                ('fecha_solicitud_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('requiere_reembolso', models.BooleanField(default=False)),
                ('fecha_reembolso', models.DateTimeField(blank=True, null=True)),
                ('referencia_reembolso', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedidos_pedido',
                'ordering': ['-fecha_pedido'],
            },
        ),
    ]
