# Generated by Django 5.2.14 on 2026-08-10 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0002_initial'),
        ('productos', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='carrito_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentarioproducto',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='comentarioproducto',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_direccion_envio',
            field=models.ForeignKey(blank=True, db_column='id_direccion_envio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.direccionenvio'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pago',
            name='id_pedido',
            field=models.OneToOneField(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='id_pedido',
            field=models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='id_pedido',
            field=models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='id_pedido',
            field=models.OneToOneField(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='pedidos.pedido'),
        ),
    ]
