# Generated by Django 5.2.14 on 2026-07-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='id_repartidor',
        ),
        migrations.AddField(
            model_name='entrega',
            name='numero_guia',
            field=models.CharField(blank=True, db_column='numero_guia', help_text='Número de rastreo proporcionado por la paquetería externa', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entrega',
            name='paqueteria',
            field=models.CharField(choices=[('99MINUTOS', '99 Minutos'), ('REDPACK', 'Redpack / J&T Express')], db_column='paqueteria', default='99MINUTOS', max_length=50),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de asignación'), ('en_ruta', 'En camino'), ('entregado', 'Entregado'), ('incidente', 'Incidente reportado')], default='pendiente', max_length=20),
        ),
        migrations.DeleteModel(
            name='Repartidor',
        ),
    ]
