# Generated by Django 5.2.14 on 2026-07-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_remove_entrega_id_repartidor_entrega_numero_guia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('oxxo', 'Pago en OXXO')], default='transferencia', max_length=20),
        ),
    ]
