# Generated by Django 5.2.14 on 2026-07-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pago_comprobante_alter_pago_metodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='fecha_vencimiento_oxxo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='referencia_oxxo',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('oxxo', 'Pago en OXXO'), ('tarjeta', 'Tarjeta de Crédito/Débito')], default='transferencia', max_length=20),
        ),
    ]
