# Generated by Django 6.0.7 on 2026-07-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pago_fecha_vencimiento_oxxo_pago_referencia_oxxo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='entrega',
            name='respuesta_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='entrega',
            name='servicio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='entrega',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='entrega',
            name='transportista',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pago',
            name='mercadopago_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pago',
            name='proveedor_pago',
            field=models.CharField(default='manual', max_length=50),
        ),
        migrations.AddField(
            model_name='pago',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('pagado', 'Pagado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='paqueteria',
            field=models.CharField(db_column='paqueteria', default='', max_length=50),
        ),
    ]
