# Generated by Django 6.0.7 on 2026-07-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_entrega_costo_envio_entrega_respuesta_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de asignación'), ('en_ruta', 'En camino'), ('en_transito', 'En tránsito'), ('entregado', 'Entregado'), ('incidente', 'Incidente reportado')], default='pendiente', max_length=20),
        ),
    ]
