# Generated by Django 6.0.5 on 2026-06-28 20:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=100, verbose_name='Apellido materno')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('es_productor', models.BooleanField(default=False)),
                ('correo_verificado', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios_usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DireccionEnvio',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_referencia', models.CharField(help_text='Ej: Casa, Oficina', max_length=100, verbose_name='Nombre de referencia')),
                ('calle', models.CharField(max_length=200)),
                ('numero_exterior', models.CharField(blank=True, max_length=10)),
                ('numero_interior', models.CharField(blank=True, max_length=10)),
                ('colonia', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('telefono_contacto', models.CharField(blank=True, max_length=15)),
                ('es_principal', models.BooleanField(default=False)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dirección de envío',
                'verbose_name_plural': 'Direcciones de envío',
                'db_table': 'usuarios_direccion_envio',
            },
        ),
        migrations.CreateModel(
            name='TokenRecuperacion',
            fields=[
                ('id_token', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=32)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='tokens_recuperacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de recuperación',
                'verbose_name_plural': 'Tokens de recuperación',
                'db_table': 'usuarios_token_recuperacion',
            },
        ),
        migrations.CreateModel(
            name='TokenVerificacion',
            fields=[
                ('id_token', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=32)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='tokens_verificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de verificación',
                'verbose_name_plural': 'Tokens de verificación',
                'db_table': 'usuarios_token_verificacion',
            },
        ),
    ]
