# Generated by Django 5.2.14 on 2026-07-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenrecuperacion',
            name='token',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='tokenverificacion',
            name='token',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
