# Generated by Django 6.0.7 on 2026-07-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_jwt_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccionenvio',
            name='pais',
            field=models.CharField(default='MX', max_length=2),
        ),
    ]
