# Generated by Django 6.0.7 on 2026-07-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_direccionenvio_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccionenvio',
            name='referencias',
            field=models.TextField(blank=True),
        ),
    ]
