# Generated by Django 6.0.5 on 2026-07-29 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_direccionenvio_referencias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='es_productor',
        ),
    ]
