# Generated by Django 5.2.14 on 2026-08-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_usuario_es_productor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
