# Generated by Django 5.2.14 on 2026-08-10 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuario_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccionenvio',
            name='id_direccion',
        ),
        migrations.RemoveField(
            model_name='direccionenvio',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='tokenrecuperacion',
            name='id_token',
        ),
        migrations.RemoveField(
            model_name='tokenrecuperacion',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='tokenverificacion',
            name='id_token',
        ),
        migrations.RemoveField(
            model_name='tokenverificacion',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='direccionenvio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='direccionenvio',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tokenrecuperacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='tokenrecuperacion',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tokens_recuperacion', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tokenverificacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='tokenverificacion',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tokens_verificacion', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
