# Generated by Django 5.2.14 on 2026-08-10 23:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icono', models.CharField(blank=True, max_length=50)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'productos_categoria',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id_favorito', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'db_table': 'productos_favorito',
                'ordering': ['-fecha_agregado'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion_corta', models.CharField(max_length=300)),
                ('descripcion_larga', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('costo_promedio', models.DecimalField(decimal_places=2, default=0, help_text='Costo promedio de adquisición (calculado automáticamente)', max_digits=10)),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramo'), ('unidad', 'Unidad'), ('libra', 'Libra'), ('docena', 'Docena'), ('caja', 'Caja')], default='kg', max_length=20)),
                ('peso_kg', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('alto_cm', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ancho_cm', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('largo_cm', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('es_destacado', models.BooleanField(default=False)),
                ('es_nuevo', models.BooleanField(default=False)),
                ('es_organico', models.BooleanField(default=False)),
                ('imagen_principal', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('temporada', models.CharField(blank=True, max_length=100)),
                ('origen', models.CharField(blank=True, max_length=100)),
                ('certificaciones', models.CharField(blank=True, max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('vistas', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos_producto',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ProductoAgricola',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_index=True, max_length=255)),
                ('categoria', models.CharField(choices=[('FERTILIZANTES_QUIMICOS', 'Fertilizantes químicos'), ('ABONOS_ORGANICOS', 'Abonos orgánicos'), ('AGROQUIMICOS', 'Agroquímicos'), ('BOMBAS_RIEGO', 'Bombas y riego'), ('HERRAMIENTAS_PLASTICOS', 'Herramientas y plásticos')], db_index=True, max_length=32)),
                ('uso_principal', models.TextField()),
                ('presentaciones', models.JSONField(default=list)),
                ('precio_base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('imagen_url', models.URLField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'productos',
                'ordering': ['id'],
            },
        ),
    ]
