# Generated by Django 6.0.5 on 2026-06-28 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icono', models.CharField(blank=True, max_length=50)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'productos_categoria',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion_corta', models.CharField(max_length=300)),
                ('descripcion_larga', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramo'), ('unidad', 'Unidad'), ('libra', 'Libra'), ('docena', 'Docena'), ('caja', 'Caja')], default='kg', max_length=20)),
                ('es_destacado', models.BooleanField(default=False)),
                ('es_nuevo', models.BooleanField(default=False)),
                ('es_organico', models.BooleanField(default=False)),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('temporada', models.CharField(blank=True, max_length=100)),
                ('origen', models.CharField(blank=True, max_length=100)),
                ('certificaciones', models.CharField(blank=True, max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('vistas', models.IntegerField(default=0)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos_producto',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
