# Generated by Django 6.0.7 on 2026-07-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_productoagricola'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='alto_cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='producto',
            name='ancho_cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='producto',
            name='largo_cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
    ]
