# Generated by Django 6.0.5 on 2026-07-30 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_rolpanel_puede_gestionar_direcciones_envio'),
        ('productos', '0004_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id_proveedor',
            field=models.ForeignKey(blank=True, db_column='id_proveedor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='admin_panel.proveedor', verbose_name='Proveedor'),
        ),
    ]
