# Generated by Django 6.0.5 on 2026-07-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_producto_id_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo_promedio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo promedio de adquisición (calculado automáticamente)', max_digits=10),
        ),
    ]
