# Generated by Django 5.2.14 on 2026-08-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_categoria_activo_categoria_fecha_actializacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='fecha_actializacion',
            new_name='fecha_actualizacion',
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
