# Generated by Django 5.2.14 on 2026-08-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaReparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('municipio', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('codigo_postal_inicio', models.CharField(max_length=5)),
                ('codigo_postal_fin', models.CharField(max_length=5)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tiempo_entrega', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Zona de reparto',
                'verbose_name_plural': 'Zonas de reparto',
                'ordering': ('estado', 'municipio', 'codigo_postal_inicio'),
            },
        ),
    ]
